apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels: 
    app: flask-app
spec:
  containers:
  - name: flask-app
    image: maxmcf13/myapp:latest
    ports:
    - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP